version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  mongodb:
    image: mongo:8.0
    container_name: ${PROJECT}-mongo
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on the default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Set the admin username
      MONGO_INITDB_ROOT_PASSWORD: password # Set the admin password
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
      - mongo-config:/data/configdb # Persist MongoDB configuration
    networks:
      - app-network

  user:
    container_name: ${PROJECT}-user
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file:
      - ./docker/env/user/.env
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=development
    volumes:
      - ./user:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules # Preserve node_modules in container
    command: npm run dev # Override to use dev command
    networks:
      - app-network

  chat:
    container_name: ${PROJECT}-chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    env_file:
      - ./docker/env/chat/.env
    ports:
      - "8082:8082"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=development
    volumes:
      - ./chat:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules # Preserve node_modules in container
    command: npm run dev # Override to use dev command
    networks:
      - app-network

  notification:
    container_name: ${PROJECT}-notification
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./docker/env/notification/.env
    ports:
      - "8083:8083"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=development
    volumes:
      - ./notification-service:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules # Preserve node_modules in container
    command: npm run dev # Override to use dev command
    networks:
      - app-network

  frontend:
    container_name: ${PROJECT}-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "5173:5173"
    env_file:
      - ./docker/env/frontend/.env
    volumes:
      - ./frontend:/usr/src/app # Mount entire project
      - /usr/src/app/node_modules # Preserve node_modules in container
    command: npm run dev # Override to use dev command
    networks:
      - app-network
  nginx:
    container_name: ${PROJECT}-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - user
      - chat
      - notification
      - frontend
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:4-management
    container_name: ${PROJECT}-rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user # Set RabbitMQ default user
      RABBITMQ_DEFAULT_PASS: password # Set RabbitMQ default password

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
